// <auto-generated />
using System;
using Fepi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fepi.Api.Migrations
{
    [DbContext(typeof(FepiDbContext))]
    [Migration("20260628144846_AddAlertasFiniquito")]
    partial class AddAlertasFiniquito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fepi.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("EntidadReferenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadReferenciaTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RolDestino")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Fepi.Api.Models.AlertaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadRelacionada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AlertasUsuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.ArchivoEvidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<int>("EntidadRelacionada")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreGuardado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RutaLocal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioSubioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSubioId");

                    b.ToTable("ArchivosEvidencia");
                });

            modelBuilder.Entity("Fepi.Api.Models.AvanceDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CantidadEjecutada")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ConceptoContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ConceptoContratoId");

                    b.HasIndex("ContratoId");

                    b.ToTable("AvancesDiarios");
                });

            modelBuilder.Entity("Fepi.Api.Models.AvanceEvidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvanceDiarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AvanceDiarioId");

                    b.ToTable("AvanceEvidencias");
                });

            modelBuilder.Entity("Fepi.Api.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BitacoraNotaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsEmisor")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Firmado")
                        .HasColumnType("boolean");

                    b.Property<int>("OrdenFirma")
                        .HasColumnType("integer");

                    b.Property<int>("RolFirmante")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BitacoraNotaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BitacoraFirmas");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorRegistroId")
                        .HasColumnType("integer");

                    b.Property<int>("BitacoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("FechaEvento")
                        .HasColumnType("date");

                    b.Property<int?>("NotaGeneradaId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFotografia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorRegistroId");

                    b.HasIndex("BitacoraId");

                    b.HasIndex("NotaGeneradaId");

                    b.ToTable("BitacoraIncidencias");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraMinuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BitacoraId")
                        .HasColumnType("integer");

                    b.Property<string>("ContenidoAcuerdos")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BitacoraId");

                    b.ToTable("BitacoraMinutas");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraMinutaParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BitacoraMinutaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreParticipante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("BitacoraMinutaId");

                    b.ToTable("BitacoraMinutaParticipantes");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("AutorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("BitacoraId")
                        .HasColumnType("integer");

                    b.Property<int?>("BitacoraTipoNotaId")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadFirmasRequeridas")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("EstadoFirma")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Folio")
                        .HasColumnType("integer");

                    b.Property<int?>("FolioVinculadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoNotaCatalogoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("BitacoraTipoNotaId");

                    b.HasIndex("FolioVinculadoId");

                    b.HasIndex("TipoNotaCatalogoId");

                    b.HasIndex("BitacoraId", "Folio")
                        .IsUnique();

                    b.ToTable("BitacoraNotas");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraTipoNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("BitacoraTiposNota");
                });

            modelBuilder.Entity("Fepi.Api.Models.CaratulaBitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abierta")
                        .HasColumnType("boolean");

                    b.Property<int>("BitacoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Contratista")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaTerminoProgramada")
                        .HasColumnType("date");

                    b.Property<string>("FolioBitacora")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("MontoContratadoConIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontoContratadoSinIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NombreContrato")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Residente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("ResidenteObraUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Superintendente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("SuperintendenteUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("SupervisorObraUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoContrato")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BitacoraId")
                        .IsUnique();

                    b.HasIndex("FolioBitacora")
                        .IsUnique();

                    b.ToTable("CaratulasBitacora");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConceptoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CantidadContratada")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConvenioModificatorioId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsExtraordinario")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("SeccionConceptoId")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ConvenioModificatorioId");

                    b.HasIndex("SeccionConceptoId");

                    b.ToTable("ConceptosContrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DependenciaContratante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaTermino")
                        .HasColumnType("date");

                    b.Property<decimal>("IVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteSinIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ModalidadPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoAnticipo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NombreObra")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NumeroLicitacion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("NumeroPeriodos")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeAnticipo")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ResidenteNombre")
                        .HasColumnType("text");

                    b.Property<string>("SuperintendenteNombre")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorExternoNombre")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPeriodo")
                        .HasColumnType("integer");

                    b.Property<string>("UbicacionExacta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NumeroContrato")
                        .IsUnique();

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampoAfectado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConvenioModificatorioId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionCambio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioModificatorioId");

                    b.ToTable("ConvenioCambios");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioModificatorioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioModificatorioId");

                    b.ToTable("ConvenioDocumentos");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioModificatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("MontoSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NumeroConvenio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("PlazoDiasSolicitado")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("VariacionAcumuladaPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("ConveniosModificatorios");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioPromocionResidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioModificatorioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioModificatorioId")
                        .IsUnique();

                    b.HasIndex("ResidenteId");

                    b.ToTable("ConvenioPromocionesResidencia");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioResolucionDependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<int>("ConvenioModificatorioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UsuarioDependenciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioModificatorioId")
                        .IsUnique();

                    b.HasIndex("UsuarioDependenciaId");

                    b.ToTable("ConvenioResolucionesDependencia");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioRevisionSupervision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioModificatorioId")
                        .HasColumnType("integer");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioModificatorioId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("ConvenioRevisionesSupervision");
                });

            modelBuilder.Entity("Fepi.Api.Models.DocumentoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("DocumentosContrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RepresentanteUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepresentanteUsuarioId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Fepi.Api.Models.EntregaRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoGarantiasDescripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EstadoObraDescripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("EntregasRecepcion");
                });

            modelBuilder.Entity("Fepi.Api.Models.EntregaRecepcionEvidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntregaRecepcionId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EntregaRecepcionId");

                    b.ToTable("EntregaRecepcionEvidencias");
                });

            modelBuilder.Entity("Fepi.Api.Models.Estimacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivoComprobantePagoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacionResidencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAprobacionSupervision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoPagadoAcumulado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("NumeroEstimacion")
                        .HasColumnType("integer");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("PeriodoContratoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioAprobacionResidenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioAprobacionSupervisionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEnvioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoComprobantePagoId");

                    b.HasIndex("PeriodoContratoId");

                    b.HasIndex("UsuarioAprobacionResidenciaId");

                    b.HasIndex("UsuarioAprobacionSupervisionId");

                    b.HasIndex("UsuarioEnvioId");

                    b.HasIndex("ContratoId", "NumeroEstimacion")
                        .IsUnique();

                    b.ToTable("Estimaciones");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionConcepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadAcumuladaActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CantidadAcumuladaAnterior")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CantidadEjecutadaPeriodo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CantidadPorEjecutar")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ConceptoContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstimacionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecioUnitarioActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoContratoId");

                    b.HasIndex("EstimacionId");

                    b.ToTable("EstimacionConceptos");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstimacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EstimacionId");

                    b.ToTable("EstimacionDocumentos");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer");

                    b.Property<int>("EstimacionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstimacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstimacionHistoriales");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionNotaBitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstimacionId")
                        .HasColumnType("integer");

                    b.Property<int>("NotaBitacoraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstimacionId");

                    b.HasIndex("NotaBitacoraId");

                    b.ToTable("EstimacionNotasBitacora");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionObservacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstimacionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstimacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstimacionObservaciones");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstimacionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ReferenciaBancaria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("UsuarioRegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstimacionId");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("EstimacionPagos");
                });

            modelBuilder.Entity("Fepi.Api.Models.Finiquito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalDeductivas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPendiente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalRetenciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UrlReporteFiniquito")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Finiquitos");
                });

            modelBuilder.Entity("Fepi.Api.Models.FiniquitoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BitacoraNotaCierreId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Deductivas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFiniquito")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicioCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ImporteContratoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteContratoOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteConvenios")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteEstimadoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteFinalAFiniquitar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImportePagadoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("PenasConvencionales")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Retenciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BitacoraNotaCierreId");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.HasIndex("CreadoPorUsuarioId");

                    b.ToTable("FiniquitosContrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.Garantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Vigencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Garantias");
                });

            modelBuilder.Entity("Fepi.Api.Models.PeriodoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "Numero")
                        .IsUnique();

                    b.ToTable("PeriodosContrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoProgramado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("PorcentajeProgramado")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("ProgramaObraItems");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvanceParcialPlanificado")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("ImportePlanificadoPeriodo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PeriodoContratoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajePlanificadoPeriodo")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("ProgramaObraSeccionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoContratoId");

                    b.HasIndex("ProgramaObraSeccionId");

                    b.ToTable("ProgramaObraPeriodos");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraSeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoFinId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoInicioId")
                        .HasColumnType("integer");

                    b.Property<int>("SeccionConceptoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PeriodoFinId");

                    b.HasIndex("PeriodoInicioId");

                    b.HasIndex("SeccionConceptoId");

                    b.ToTable("ProgramaObraSecciones");
                });

            modelBuilder.Entity("Fepi.Api.Models.RegistroDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResponsableUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ResponsableUsuarioId");

                    b.ToTable("RegistrosDiarios");
                });

            modelBuilder.Entity("Fepi.Api.Models.SeccionConcepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("SeccionesConcepto");
                });

            modelBuilder.Entity("Fepi.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Fepi.Api.Models.UsuarioContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("UsuarioId", "ContratoId", "Rol")
                        .IsUnique();

                    b.ToTable("UsuarioContratos");
                });

            modelBuilder.Entity("Fepi.Api.Models.Alerta", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.AlertaUsuario", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fepi.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.ArchivoEvidencia", b =>
                {
                    b.HasOne("Fepi.Api.Models.Usuario", "UsuarioSubio")
                        .WithMany()
                        .HasForeignKey("UsuarioSubioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioSubio");
                });

            modelBuilder.Entity("Fepi.Api.Models.AvanceDiario", b =>
                {
                    b.HasOne("Fepi.Api.Models.Usuario", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.ConceptoContrato", "ConceptoContrato")
                        .WithMany()
                        .HasForeignKey("ConceptoContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("ConceptoContrato");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.AvanceEvidencia", b =>
                {
                    b.HasOne("Fepi.Api.Models.AvanceDiario", "AvanceDiario")
                        .WithMany("Evidencias")
                        .HasForeignKey("AvanceDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvanceDiario");
                });

            modelBuilder.Entity("Fepi.Api.Models.Bitacora", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraFirma", b =>
                {
                    b.HasOne("Fepi.Api.Models.BitacoraNota", "BitacoraNota")
                        .WithMany("Firmas")
                        .HasForeignKey("BitacoraNotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BitacoraNota");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraIncidencia", b =>
                {
                    b.HasOne("Fepi.Api.Models.Usuario", "ActorRegistro")
                        .WithMany()
                        .HasForeignKey("ActorRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Bitacora", "Bitacora")
                        .WithMany("Incidencias")
                        .HasForeignKey("BitacoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.BitacoraNota", "NotaGenerada")
                        .WithMany()
                        .HasForeignKey("NotaGeneradaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorRegistro");

                    b.Navigation("Bitacora");

                    b.Navigation("NotaGenerada");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraMinuta", b =>
                {
                    b.HasOne("Fepi.Api.Models.Bitacora", "Bitacora")
                        .WithMany("Minutas")
                        .HasForeignKey("BitacoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bitacora");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraMinutaParticipante", b =>
                {
                    b.HasOne("Fepi.Api.Models.BitacoraMinuta", "BitacoraMinuta")
                        .WithMany("Participantes")
                        .HasForeignKey("BitacoraMinutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitacoraMinuta");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraNota", b =>
                {
                    b.HasOne("Fepi.Api.Models.Usuario", "AutorUsuario")
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Bitacora", "Bitacora")
                        .WithMany("Notas")
                        .HasForeignKey("BitacoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.BitacoraTipoNota", null)
                        .WithMany("Notas")
                        .HasForeignKey("BitacoraTipoNotaId");

                    b.HasOne("Fepi.Api.Models.BitacoraNota", "FolioVinculado")
                        .WithMany()
                        .HasForeignKey("FolioVinculadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fepi.Api.Models.BitacoraTipoNota", "TipoNotaCatalogo")
                        .WithMany()
                        .HasForeignKey("TipoNotaCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AutorUsuario");

                    b.Navigation("Bitacora");

                    b.Navigation("FolioVinculado");

                    b.Navigation("TipoNotaCatalogo");
                });

            modelBuilder.Entity("Fepi.Api.Models.CaratulaBitacora", b =>
                {
                    b.HasOne("Fepi.Api.Models.Bitacora", "Bitacora")
                        .WithOne("Caratula")
                        .HasForeignKey("Fepi.Api.Models.CaratulaBitacora", "BitacoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bitacora");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConceptoContrato", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("ConceptoContratos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.ConvenioModificatorio", "ConvenioModificatorio")
                        .WithMany()
                        .HasForeignKey("ConvenioModificatorioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fepi.Api.Models.SeccionConcepto", "SeccionConcepto")
                        .WithMany("Conceptos")
                        .HasForeignKey("SeccionConceptoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contrato");

                    b.Navigation("ConvenioModificatorio");

                    b.Navigation("SeccionConcepto");
                });

            modelBuilder.Entity("Fepi.Api.Models.Contrato", b =>
                {
                    b.HasOne("Fepi.Api.Models.Empresa", "Empresa")
                        .WithMany("Contratos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioCambio", b =>
                {
                    b.HasOne("Fepi.Api.Models.ConvenioModificatorio", "ConvenioModificatorio")
                        .WithMany("Cambios")
                        .HasForeignKey("ConvenioModificatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConvenioModificatorio");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioDocumento", b =>
                {
                    b.HasOne("Fepi.Api.Models.ConvenioModificatorio", "ConvenioModificatorio")
                        .WithMany("Documentos")
                        .HasForeignKey("ConvenioModificatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConvenioModificatorio");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioModificatorio", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("Convenios")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioPromocionResidencia", b =>
                {
                    b.HasOne("Fepi.Api.Models.ConvenioModificatorio", "ConvenioModificatorio")
                        .WithOne("PromocionResidencia")
                        .HasForeignKey("Fepi.Api.Models.ConvenioPromocionResidencia", "ConvenioModificatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConvenioModificatorio");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioResolucionDependencia", b =>
                {
                    b.HasOne("Fepi.Api.Models.ConvenioModificatorio", "ConvenioModificatorio")
                        .WithOne("ResolucionDependencia")
                        .HasForeignKey("Fepi.Api.Models.ConvenioResolucionDependencia", "ConvenioModificatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "UsuarioDependencia")
                        .WithMany()
                        .HasForeignKey("UsuarioDependenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConvenioModificatorio");

                    b.Navigation("UsuarioDependencia");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioRevisionSupervision", b =>
                {
                    b.HasOne("Fepi.Api.Models.ConvenioModificatorio", "ConvenioModificatorio")
                        .WithOne("RevisionSupervision")
                        .HasForeignKey("Fepi.Api.Models.ConvenioRevisionSupervision", "ConvenioModificatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConvenioModificatorio");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Fepi.Api.Models.DocumentoContrato", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("Documentos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.Empresa", b =>
                {
                    b.HasOne("Fepi.Api.Models.Usuario", "RepresentanteUsuario")
                        .WithMany()
                        .HasForeignKey("RepresentanteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RepresentanteUsuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.EntregaRecepcion", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.EntregaRecepcionEvidencia", b =>
                {
                    b.HasOne("Fepi.Api.Models.EntregaRecepcion", "EntregaRecepcion")
                        .WithMany("Evidencias")
                        .HasForeignKey("EntregaRecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntregaRecepcion");
                });

            modelBuilder.Entity("Fepi.Api.Models.Estimacion", b =>
                {
                    b.HasOne("Fepi.Api.Models.ArchivoEvidencia", "ArchivoComprobantePago")
                        .WithMany()
                        .HasForeignKey("ArchivoComprobantePagoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.PeriodoContrato", "PeriodoContrato")
                        .WithMany()
                        .HasForeignKey("PeriodoContratoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fepi.Api.Models.Usuario", "UsuarioAprobacionResidencia")
                        .WithMany()
                        .HasForeignKey("UsuarioAprobacionResidenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fepi.Api.Models.Usuario", "UsuarioAprobacionSupervision")
                        .WithMany()
                        .HasForeignKey("UsuarioAprobacionSupervisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fepi.Api.Models.Usuario", "UsuarioEnvio")
                        .WithMany()
                        .HasForeignKey("UsuarioEnvioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArchivoComprobantePago");

                    b.Navigation("Contrato");

                    b.Navigation("PeriodoContrato");

                    b.Navigation("UsuarioAprobacionResidencia");

                    b.Navigation("UsuarioAprobacionSupervision");

                    b.Navigation("UsuarioEnvio");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionConcepto", b =>
                {
                    b.HasOne("Fepi.Api.Models.ConceptoContrato", "ConceptoContrato")
                        .WithMany()
                        .HasForeignKey("ConceptoContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Estimacion", "Estimacion")
                        .WithMany("Conceptos")
                        .HasForeignKey("EstimacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConceptoContrato");

                    b.Navigation("Estimacion");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionDocumento", b =>
                {
                    b.HasOne("Fepi.Api.Models.Estimacion", "Estimacion")
                        .WithMany("Documentos")
                        .HasForeignKey("EstimacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimacion");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionHistorial", b =>
                {
                    b.HasOne("Fepi.Api.Models.Estimacion", "Estimacion")
                        .WithMany("Historial")
                        .HasForeignKey("EstimacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estimacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionNotaBitacora", b =>
                {
                    b.HasOne("Fepi.Api.Models.Estimacion", "Estimacion")
                        .WithMany("NotasVinculadas")
                        .HasForeignKey("EstimacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.BitacoraNota", "NotaBitacora")
                        .WithMany()
                        .HasForeignKey("NotaBitacoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estimacion");

                    b.Navigation("NotaBitacora");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionObservacion", b =>
                {
                    b.HasOne("Fepi.Api.Models.Estimacion", "Estimacion")
                        .WithMany("Observaciones")
                        .HasForeignKey("EstimacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estimacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.EstimacionPago", b =>
                {
                    b.HasOne("Fepi.Api.Models.Estimacion", "Estimacion")
                        .WithMany("Pagos")
                        .HasForeignKey("EstimacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estimacion");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("Fepi.Api.Models.Finiquito", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.FiniquitoContrato", b =>
                {
                    b.HasOne("Fepi.Api.Models.BitacoraNota", "BitacoraNotaCierre")
                        .WithMany()
                        .HasForeignKey("BitacoraNotaCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BitacoraNotaCierre");

                    b.Navigation("Contrato");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Fepi.Api.Models.Garantia", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("Garantias")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.PeriodoContrato", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("Periodos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraItem", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("ProgramaObra")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraPeriodo", b =>
                {
                    b.HasOne("Fepi.Api.Models.PeriodoContrato", "PeriodoContrato")
                        .WithMany()
                        .HasForeignKey("PeriodoContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.ProgramaObraSeccion", "ProgramaObraSeccion")
                        .WithMany("Periodos")
                        .HasForeignKey("ProgramaObraSeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoContrato");

                    b.Navigation("ProgramaObraSeccion");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraSeccion", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("ProgramaObraSecciones")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.PeriodoContrato", "PeriodoFin")
                        .WithMany()
                        .HasForeignKey("PeriodoFinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.PeriodoContrato", "PeriodoInicio")
                        .WithMany()
                        .HasForeignKey("PeriodoInicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.SeccionConcepto", "SeccionConcepto")
                        .WithMany()
                        .HasForeignKey("SeccionConceptoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("PeriodoFin");

                    b.Navigation("PeriodoInicio");

                    b.Navigation("SeccionConcepto");
                });

            modelBuilder.Entity("Fepi.Api.Models.RegistroDiario", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "ResponsableUsuario")
                        .WithMany()
                        .HasForeignKey("ResponsableUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("ResponsableUsuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.SeccionConcepto", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("SeccionesConcepto")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Fepi.Api.Models.UsuarioContrato", b =>
                {
                    b.HasOne("Fepi.Api.Models.Contrato", "Contrato")
                        .WithMany("Usuarios")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fepi.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fepi.Api.Models.AvanceDiario", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Fepi.Api.Models.Bitacora", b =>
                {
                    b.Navigation("Caratula");

                    b.Navigation("Incidencias");

                    b.Navigation("Minutas");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraMinuta", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraNota", b =>
                {
                    b.Navigation("Firmas");
                });

            modelBuilder.Entity("Fepi.Api.Models.BitacoraTipoNota", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Fepi.Api.Models.Contrato", b =>
                {
                    b.Navigation("ConceptoContratos");

                    b.Navigation("Convenios");

                    b.Navigation("Documentos");

                    b.Navigation("Garantias");

                    b.Navigation("Periodos");

                    b.Navigation("ProgramaObra");

                    b.Navigation("ProgramaObraSecciones");

                    b.Navigation("SeccionesConcepto");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Fepi.Api.Models.ConvenioModificatorio", b =>
                {
                    b.Navigation("Cambios");

                    b.Navigation("Documentos");

                    b.Navigation("PromocionResidencia");

                    b.Navigation("ResolucionDependencia");

                    b.Navigation("RevisionSupervision");
                });

            modelBuilder.Entity("Fepi.Api.Models.Empresa", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Fepi.Api.Models.EntregaRecepcion", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Fepi.Api.Models.Estimacion", b =>
                {
                    b.Navigation("Conceptos");

                    b.Navigation("Documentos");

                    b.Navigation("Historial");

                    b.Navigation("NotasVinculadas");

                    b.Navigation("Observaciones");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Fepi.Api.Models.ProgramaObraSeccion", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("Fepi.Api.Models.SeccionConcepto", b =>
                {
                    b.Navigation("Conceptos");
                });
#pragma warning restore 612, 618
        }
    }
}
