// app/constants/strings.ts
/**
 * Centralized Spanish (es-MX) UI strings. Single place to edit copy; if real
 * i18n is ever needed, this becomes the default locale file. Not auto-imported
 * — import explicitly: `import { S } from '~/constants/strings'`.
 */
export const S = {
  app: {
    name: 'Gestor de Contratos',
    shortName: 'Contratos',
  },
  common: {
    save: 'Guardar',
    send: 'Enviar',
    saveAndSend: 'Guardar y enviar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    back: 'Regresar',
    loading: 'Cargando…',
    search: 'Buscar',
    empty: 'Sin información',
    error: 'Ocurrió un error',
  },
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Ingresa con tu usuario y contraseña',
    username: 'Usuario',
    password: 'Contraseña',
    submit: 'Entrar',
    usernameRequired: 'Ingresa tu usuario',
    passwordRequired: 'Ingresa tu contraseña',
    invalidCredentials: 'Usuario o contraseña incorrectos',
  },
  nav: {
    myContracts: 'Mis contratos',
    users: 'Usuarios',
    dashboard: 'Tablero',
    logbook: 'Bitácora',
    estimates: 'Estimaciones',
    schedule: 'Programa de obra',
    financial: 'Financiero',
    concepts: 'Catálogo de conceptos',
    evidence: 'Evidencias',
    files: 'Archivos',
    contract: 'Contrato',
    logout: 'Cerrar sesión',
  },
  roles: {
    admin: 'Administrador',
    resident: 'Residente',
    superintendent: 'Superintendente',
    supervisor: 'Supervisor',
    financial: 'Finanzas',
  },
  estimateStatus: {
    draft: 'Borrador',
    submitted: 'Enviada',
    with_notes: 'Con notas',
    rejected: 'Rechazada',
    approved: 'Aprobada',
    paid: 'Pagada',
  },
  agreementStatus: {
    draft: 'Borrador',
    submitted: 'Enviado',
    with_notes: 'Con notas',
    rejected: 'Rechazado',
    approved: 'Aprobado',
  },
  contractStatus: {
    active: 'Activo',
    closing: 'En cierre',
    closed: 'Cerrado',
  },
  dashboard: {
    title: 'Mis contratos',
    newContract: 'Nuevo contrato',
    empty: 'No tienes contratos asignados.',
    physicalProgress: 'Avance físico',
    executed: 'Ejercido',
    contracted: 'Contratado',
    alerts: 'Tienes alertas en este contrato',
  },
  contractDashboard: {
    balance: 'Balance',
    anticipo: 'Anticipo',
    overSchedule: 'Avance vs programa',
    programmed: 'Programado',
    actual: 'Real',
    physical: 'Físico',
    financial: 'Financiero',
    recentLogbook: 'Bitácora reciente',
    recentEstimates: 'Estimaciones recientes',
    viewAll: 'Ver todo',
    folio: 'Folio',
    noLogNotes: 'Sin notas de bitácora',
    noEstimates: 'Sin estimaciones',
    legend: 'Estados',
  },
  actions: {
    newLogNote: 'Nueva nota',
    uploadEvidence: 'Subir evidencia',
    conceptCatalog: 'Catálogo de conceptos',
    schedule: 'Programa de obra',
    files: 'Archivos',
  },
  conceptCatalog: {
    title: 'Catálogo de conceptos',
    empty: 'Este contrato no tiene conceptos registrados.',
    readonlyNotice: 'El catálogo es de solo lectura. Para modificar conceptos inicia un convenio modificatorio.',
    newAgreement: 'Nuevo convenio',
    columns: {
      specification: 'Especificación',
      description: 'Descripción',
      unit: 'Unidad',
      unitPrice: 'P.U.',
      contractedQty: 'Vol. contratado',
      contractedAmount: 'Importe contratado',
      executed: 'Vol. ejecutado',
      executedAmount: 'Importe ejecutado',
      remaining: 'Vol. por ejecutar',
    },
    search: 'Buscar concepto…',
    total: 'Total contratado',
  },
  estimateForm: {
    title: 'Nueva estimación',
    editTitlePrefix: 'Editar estimación',
    saveDraft: 'Guardar borrador',
    saveChanges: 'Guardar cambios',
    // Section anchors (one scrolling page)
    sections: {
      cover: 'Portada',
      concepts: 'Conceptos',
      summary: 'Resumen',
      attachments: 'Anexos',
    },
    // Cover
    cover: {
      contract: 'Contrato',
      object: 'Objeto del contrato',
      contractor: 'Contratista',
      number: 'Estimación No.',
      anticipo: 'Anticipo',
      periodFrom: 'Del',
      periodTo: 'Al',
      periodHint: 'Periodo que abarca la estimación',
    },
    // Concept selection (picker before the grid)
    conceptPicker: {
      label: 'Conceptos incluidos en esta estimación',
      hint: 'Selecciona los conceptos del catálogo que aplican. Solo los marcados aparecen en la cuadrícula.',
      addAll: 'Agregar todos',
      clearAll: 'Quitar todos',
      noMatch: 'Sin coincidencias',
      selected: 'seleccionados',
    },
    // Cell-color legend
    legend: {
      title: 'Colores',
      editable: 'Editable',
      calculated: 'Calculado',
      readonly: 'Solo lectura',
    },
    // 11 grid columns
    columns: {
      number: 'No.',
      specification: 'Especificación',
      description: 'Descripción',
      unit: 'Unidad',
      inProject: 'Vol. contratado',
      upToLast: 'Estimado anterior',
      inThisEstimate: 'En esta estimación',
      totalEstimated: 'Total estimado',
      toExecute: 'Por ejecutar',
      unitPrice: 'P.U.',
      totalAmount: 'Importe',
    },
    // Summary table 1 (concept rollup) + table 2 (calculations)
    summary: {
      conceptsTitle: 'Resumen por concepto',
      calculationsTitle: 'Cálculo de la estimación',
      subtotal: 'Subtotal',
      estimateAmount: 'Importe de la estimación',
      iva: 'IVA',
      estimateTotal: 'Total',
      anticipoAmortization: 'Amortización de anticipo',
      amortizationIva: 'IVA de la amortización',
      amortizationTotal: 'Total de amortización',
      retentions: 'Retenciones / fondo de garantía',
      cincoAlMillar: '5 al millar (SFP)',
      net: 'Total a pagar',
    },
    // Attachments
    attachments: {
      title: 'Anexos',
      linkHint: 'Vincula evidencias y notas de bitácora a esta estimación.',
      logNotes: 'Notas de bitácora',
      files: 'Archivos',
      logNotesEmpty: 'No hay notas de bitácora en este contrato.',
      filesEmpty: 'No hay archivos en este contrato.',
    },
    // Validation / empty states
    validation: {
      noConcepts: 'Este contrato no tiene conceptos en el catálogo.',
      periodRequired: 'Indica el periodo de la estimación.',
      periodOrder: 'La fecha de término no puede ser anterior a la de inicio.',
      noQuantities: 'Captura al menos un volumen para crear la estimación.',
      overContracted: 'Hay conceptos que superan el volumen contratado.',
      overRow: 'Supera el volumen contratado',
    },
  },
  estimateDetail: {
    titlePrefix: 'Estimación',
    period: 'Periodo',
    sections: {
      concepts: 'Conceptos',
      summary: 'Resumen',
      signatures: 'Firmas',
      history: 'Historial',
      attachments: 'Anexos',
    },
    signatures: {
      signed: 'Firmada',
      pending: 'Pendiente',
      signedAt: 'Firmó',
      unsigned: 'Sin firmar',
    },
    review: {
      title: 'Revisión',
    },
    attachmentsEmpty: 'Esta estimación no tiene anexos.',
    linkedLogNotes: 'Notas de bitácora vinculadas',
    evidence: 'Evidencias',
    // Workflow action buttons
    // NOTE: 'approve' is removed — signing IS approving. The last of the three
    // required signatures auto-transitions the estimate to 'approved'.
    actions: {
      edit: 'Editar',
      submit: 'Enviar a revisión',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
      markPaid: 'Marcar como pagada',
      sign: 'Firmar y aprobar',
    },
    // Note modal (return / reject)
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar estimación',
      label: 'Motivo',
      placeholder: 'Describe el motivo de la devolución o rechazo…',
      required: 'Escribe el motivo.',
    },
    // Highlighted banner for the latest returned/rejected note
    banner: {
      withNotes: 'Devuelta con notas',
      rejected: 'Rechazada',
    },
  },
  workflow: {
    created: 'Creada',
    submitted: 'Enviada a revisión',
    returned_with_notes: 'Devuelta con notas',
    rejected: 'Rechazada',
    approved: 'Aprobada',
    paid: 'Pagada',
    signed: 'Firmada',
    reopened: 'Reabierta',
  },
  contractInfo: {
    title: 'Información del contrato',
    sections: {
      general: 'Datos generales',
      parties: 'Partes',
      agreements: 'Convenios modificatorios',
      closing: 'Cierre del contrato',
    },
    fields: {
      code: 'Clave / licitación',
      title: 'Objeto del contrato',
      status: 'Estado',
      amount: 'Monto contratado',
      anticipo: 'Porcentaje de anticipo',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de terminación',
      resident: 'Residente',
      superintendent: 'Superintendente',
      supervisor: 'Supervisor',
      financial: 'Finanzas',
      contractor: 'Contratista',
    },
    agreements: {
      empty: 'Sin convenios modificatorios.',
      new: 'Nuevo convenio',
      number: 'Convenio No.',
      kindLabel: { amount: 'Monto', time: 'Plazo', mixed: 'Mixto' },
    },
    closing: {
      reception: 'Acta de recepción',
      finiquito: 'Finiquito',
      notStarted: 'No iniciado',
      initiate: 'Iniciar',
      view: 'Ver',
      finiquitoBlocked: 'Disponible una vez aprobada el acta de recepción',
    },
  },
  agreement: {
    titlePrefix: 'Convenio',
    newTitle: 'Nuevo convenio modificatorio',
    editTitlePrefix: 'Editar convenio',
    kind: { amount: 'Modificación de monto', time: 'Modificación de plazo', mixed: 'Modificación mixta' },
    fields: {
      description: 'Descripción del convenio',
      descriptionPlaceholder: 'Describe el alcance del convenio modificatorio…',
      amountDelta: 'Variación de monto (MXN)',
      amountDeltaHint: 'Positivo = ampliación, negativo = reducción. Deja en blanco si no aplica.',
      timeDeltaDays: 'Variación de plazo (días)',
      timeDeltaHint: 'Positivo = ampliación, negativo = reducción. Deja en blanco si no aplica.',
    },
    saveDraft: 'Guardar borrador',
    saveChanges: 'Guardar cambios',
    actions: {
      submit: 'Enviar a firma',
      sign: 'Firmar y aprobar',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
      edit: 'Editar',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar convenio',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
    },
    banner: { withNotes: 'Devuelto con notas', rejected: 'Rechazado' },
    sections: { detail: 'Detalle', signatures: 'Firmas', history: 'Historial' },
    effectNotice: 'Al aprobarse, la variación de plazo se aplica a la fecha de término. El monto lo recalcula el sistema.',
    conceptChanges: {
      title: 'Cambios a conceptos existentes',
      hint: 'Selecciona conceptos del catálogo y modifica los campos que cambien en este convenio.',
      addConcept: 'Agregar concepto',
      empty: 'Sin conceptos modificados.',
      columns: {
        specification: 'Especificación',
        description: 'Descripción',
        currentQty: 'Vol. actual',
        newQty: 'Nuevo vol.',
        currentPrice: 'P.U. actual',
        newPrice: 'Nuevo P.U.',
        currentStart: 'Inicio actual',
        newStart: 'Nuevo inicio',
        currentEnd: 'Término actual',
        newEnd: 'Nuevo término',
        remove: 'Quitar',
      },
    },
    newConcepts: {
      title: 'Conceptos nuevos',
      hint: 'Estos conceptos se agregarán al catálogo al aprobarse el convenio.',
      add: 'Agregar concepto nuevo',
      empty: 'Sin conceptos nuevos.',
      columns: {
        specification: 'Especificación',
        description: 'Descripción',
        unit: 'Unidad',
        qty: 'Vol.',
        unitPrice: 'P.U.',
        scheduleStart: 'Inicio programa',
        scheduleEnd: 'Término programa',
        remove: 'Quitar',
      },
      validation: {
        specRequired: 'Especificación requerida',
        descRequired: 'Descripción requerida',
        unitRequired: 'Unidad requerida',
        qtyRequired: 'Vol. debe ser mayor a 0',
        priceRequired: 'P.U. debe ser mayor a 0',
      },
    },
    summary: {
      derivedAmountDelta: 'Variación neta de monto',
      derivedTimeDelta: 'Variación de plazo',
      days: 'días',
      noChanges: 'Sin cambios de monto registrados.',
    },
    validation: {
      descriptionRequired: 'Escribe la descripción del convenio.',
      noChanges: 'Agrega al menos un cambio a un concepto, concepto nuevo, sección nueva o cambio de fechas.',
    },
    contractDates: {
      title: 'Cambio de fechas del contrato',
      newStart: 'Nueva fecha de inicio',
      newEnd: 'Nueva fecha de término',
      current: 'Actual',
    },
  },
  reception: {
    title: 'Acta de recepción',
    initiate: 'Iniciar acta de recepción',
    logNoteStep: {
      title: 'Nota de bitácora de cierre',
      hint: 'Esta nota quedará vinculada automáticamente al acta de recepción.',
      titleLabel: 'Título',
      titlePlaceholder: 'Ej. Acta de entrega-recepción de obra',
      bodyLabel: 'Descripción',
      bodyPlaceholder: 'Describe el estado de la obra al momento de la recepción…',
      dateLabel: 'Fecha',
      required: 'Este campo es requerido.',
      create: 'Crear nota y continuar',
    },
    actions: {
      submit: 'Enviar a firma',
      sign: 'Firmar y aprobar',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar acta',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
    },
    banner: { withNotes: 'Devuelta con notas', rejected: 'Rechazada' },
    linkedLogNote: 'Nota de bitácora vinculada',
    sections: { signatures: 'Firmas', history: 'Historial' },
  },
  finiquito: {
    title: 'Finiquito',
    initiate: 'Iniciar finiquito',
    blockedNotice: 'El finiquito solo puede iniciarse una vez que el acta de recepción esté aprobada.',
    actions: {
      submit: 'Enviar a firma',
      sign: 'Firmar y aprobar',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar finiquito',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
    },
    banner: { withNotes: 'Devuelto con notas', rejected: 'Rechazado' },
    sections: { signatures: 'Firmas', history: 'Historial' },
  },
  newContract: {
    title: 'Nuevo contrato',
    sections: {
      general: 'Datos generales',
      rates: 'Tasas y retenciones',
      parties: 'Partes del contrato',
      concepts: 'Catálogo de conceptos',
      schedule: 'Programa de obra',
    },
    fields: {
      code: 'Clave / licitación',
      codePlaceholder: 'Ej. LPI-SRO-2025-001',
      title: 'Objeto del contrato',
      titlePlaceholder: 'Describe el objeto de la obra o servicio…',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de terminación',
      anticipoPercentage: 'Anticipo (%)',
      ivaRate: 'IVA (%)',
      retentionPercentage: 'Retenciones / fondo de garantía (%)',
      cincoAlMillar: '5 al millar SFP (%)',
      cincoAlMillarFixed: '0.5% (fijo por norma)',
      estimatePeriodicity: 'Periodicidad de estimaciones',
      periodicityMonthly: 'Mensual (una estimación por mes)',
      periodicityBiweekly: 'Quincenal (dos estimaciones por mes)',
      superintendent: 'Superintendente',
      supervisor: 'Supervisor',
      financial: 'Responsable de finanzas',
      contractor: 'Empresa contratista',
      contractorDerived: 'Se obtiene del superintendente seleccionado',
    },
    concepts: {
      hint: 'El monto del contrato se calculará como la suma de todos los conceptos.',
      add: 'Agregar concepto',
      empty: 'Agrega al menos un concepto al catálogo.',
      total: 'Monto total del contrato',
      columns: {
        specification: 'Especificación',
        description: 'Descripción',
        unit: 'Unidad',
        qty: 'Vol. contratado',
        unitPrice: 'P.U.',
        amount: 'Importe',
        remove: 'Quitar',
      },
      validation: {
        specRequired: 'Especificación requerida',
        descRequired: 'Descripción requerida',
        unitRequired: 'Unidad requerida',
        qtyPositive: 'Volumen debe ser > 0',
        pricePositive: 'P.U. debe ser > 0',
      },
    },
    schedule: {
      hint: 'Asigna un periodo de ejecución a cada concepto. Las fechas deben estar dentro del periodo del contrato.',
      ganttTitle: 'Vista previa del programa',
      columns: {
        concept: 'Concepto',
        start: 'Inicio',
        end: 'Término',
        duration: 'Días',
        amount: 'Importe',
      },
      validation: {
        startRequired: 'Fecha de inicio requerida',
        endRequired: 'Fecha de término requerida',
        startAfterContract: 'Inicio debe ser ≥ inicio del contrato',
        endBeforeContract: 'Término debe ser ≤ término del contrato',
        startAfterEnd: 'Inicio debe ser anterior al término',
      },
      allClear: 'Todas las fechas están dentro del periodo del contrato.',
    },
    validation: {
      codeRequired: 'Ingresa la clave del contrato.',
      titleRequired: 'Ingresa el objeto del contrato.',
      datesRequired: 'El periodo del contrato es requerido.',
      endBeforeStart: 'La fecha de término debe ser posterior al inicio.',
      anticipoRange: 'El anticipo debe estar entre 0% y 100%.',
      ivaRange: 'El IVA debe estar entre 0% y 100%.',
      retentionRange: 'La retención debe estar entre 0% y 100%.',
      superintendentRequired: 'Selecciona un superintendente.',
      supervisorRequired: 'Selecciona un supervisor.',
      conceptsRequired: 'Agrega al menos un concepto.',
      scheduleRequired: 'Todos los conceptos deben tener fechas de programa.',
      scheduleOutOfRange: 'Hay fechas fuera del periodo del contrato.',
    },
    files: {
      title: 'Archivos iniciales del contrato',
      hint: 'Sube los documentos originales del contrato. Quedarán en la carpeta "Documentos del contrato".',
      dropzone: 'Arrastra archivos aquí o haz clic para seleccionar',
      dropzoneActive: 'Suelta los archivos…',
      uploading: 'Subiendo',
      uploaded: 'Subido',
      failed: 'Error',
      removeQueued: 'Quitar',
      finalize: 'Ir al contrato',
      skip: 'Omitir por ahora',
      uploadAll: 'Subir todos',
      sectionNote: 'Los archivos se suben una vez creado el contrato.',
    },
    submit: 'Crear contrato',
    submitting: 'Creando…',
  },
  conceptSections: {
    sectionHeader: 'Sección',
    noSection: 'Sin sección',
    subtotal: 'Subtotal sección',
    addSection: 'Agregar sección',
    removeSection: 'Quitar sección',
    specificationNumber: 'Especificación de sección',
    description: 'Descripción de la sección',
    period: 'Periodo de la sección',
    from: 'Del',
    to: 'Al',
    validation: {
      specRequired: 'Especificación requerida',
      descRequired: 'Descripción requerida',
      datesRequired: 'El periodo de la sección es requerido',
      endBeforeStart: 'La fecha de término debe ser posterior al inicio',
      startBeforeContract: 'El inicio de la sección no puede ser anterior al inicio del contrato',
      endAfterContract: 'El término de la sección no puede ser posterior al término del contrato',
      startBeforeSection: 'El inicio del concepto no puede ser anterior al inicio de su sección',
      endAfterSection: 'El término del concepto no puede ser posterior al término de su sección',
      conceptOutOfRange: 'Hay conceptos fuera del periodo de la sección',
    },
  },
  logNoteDetail: {
    folio: 'Folio',
    date: 'Fecha',
    author: 'Autor',
    body: 'Descripción',
    attachments: 'Anexos',
    attachmentsEmpty: 'Sin anexos.',
    sections: {
      content: 'Nota',
      signatures: 'Firmas',
    },
    status: {
      locked: 'Firmada y bloqueada',
      pending: 'Pendiente de firmas',
    },
    sign: 'Firmar nota',
    signHint: 'Una vez que los tres roles firmen, la nota quedará bloqueada e inmutable.',
    alreadySigned: 'Ya firmaste esta nota.',
  },
  logNote: {
    title: 'Nota de bitácora',
    folio: 'Folio',
    date: 'Fecha',
    author: 'Autor',
    body: 'Descripción',
    attachments: 'Anexos',
    attachmentsEmpty: 'Sin anexos.',
    sections: {
      content: 'Contenido',
      signatures: 'Firmas',
    },
    status: {
      locked: 'Firmada y cerrada',
      unlocked: 'Pendiente de firmas',
    },
    actions: {
      sign: 'Firmar',
      edit: 'Editar',
    },
    lockedNotice: 'Esta nota está cerrada. Una vez que los tres roles firman, la nota queda inmutable.',
    signedNotice: 'Esta nota ha sido firmada por los tres roles y no puede editarse.',
    newTitle: 'Nueva nota de bitácora',
    fields: {
      title: 'Título',
      titlePlaceholder: 'Ej. Inicio de trazo y nivelación',
      date: 'Fecha',
      body: 'Descripción',
      bodyPlaceholder: 'Redacta la nota de bitácora aquí…',
    },
    validation: {
      titleRequired: 'El título es requerido.',
      dateRequired: 'La fecha es requerida.',
      bodyRequired: 'La descripción es requerida.',
    },
    save: 'Crear nota',
  },
  schedulePage: {
    title: 'Programa de obra',
    summary: {
      physicalProgress: 'Avance físico',
      financialProgress: 'Avance financiero',
      plannedProgress: 'Avance planeado',
      behind: 'Conceptos rezagados',
      ahead: 'Conceptos adelantados',
      onTrack: 'Al corriente',
      done: 'Completados',
      overdue: 'Vencidos',
    },
    gantt: {
      title: 'Diagrama de Gantt',
      today: 'Hoy',
      legend: {
        done: 'Completado',
        executed: 'Ejecutado',
        ahead: 'Adelantado',
        on_track: 'Al corriente',
        behind: 'Rezagado',
        overdue: 'Vencido',
        future: 'Sin iniciar',
        remaining: 'Por ejecutar',
      },
    },
    sCurve: {
      title: 'Curva S',
      programmed: 'Programado',
      physical: 'Avance físico',
      financial: 'Avance financiero',
    },
    detail: {
      concept: 'Concepto',
      planned: 'Planeado',
      actual: 'Real',
      delta: 'Diferencia',
      status: 'Estado',
      start: 'Inicio',
      end: 'Término',
    },
    statusLabel: {
      done: 'Completado',
      ahead: 'Adelantado',
      on_track: 'Al corriente',
      behind: 'Rezagado',
      overdue: 'Vencido',
      future: 'Sin iniciar',
      not_started: 'Sin iniciar',
    },
  },
  files: {
    title: 'Explorador de archivos',
    folders: {
      contract: 'Documentos del contrato',
      evidence: 'Evidencias',
      payments: 'Comprobantes de pago',
      predefinedHint: 'Carpeta predefinida (no se puede renombrar ni eliminar)',
    },
    actions: {
      newFolder: 'Nueva carpeta',
      upload: 'Subir archivos',
      rename: 'Renombrar',
      delete: 'Eliminar',
      download: 'Descargar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
    },
    upload: {
      dropHere: 'Arrastra archivos aquí o haz clic para seleccionar',
      dropActive: 'Suelta los archivos…',
      uploading: 'Subiendo',
      done: 'Listo',
      error: 'Error',
    },
    newFolderPlaceholder: 'Nombre de la carpeta',
    renamePlaceholder: 'Nuevo nombre',
    deleteFileConfirm: '¿Eliminar este archivo? Esta acción no se puede deshacer.',
    deleteFolderConfirm: '¿Eliminar esta carpeta y todo su contenido? Esta acción no se puede deshacer.',
    empty: 'Esta carpeta está vacía.',
    ownerOnly: 'Solo puedes eliminar archivos que tú subiste.',
    columns: {
      name: 'Nombre',
      size: 'Tamaño',
      uploadedBy: 'Subido por',
      uploadedAt: 'Fecha',
    },
  },
  financial: {
    title: 'Estado financiero',
    sections: {
      amounts: 'Monto contratado vs ejecutado',
      anticipo: 'Anticipo',
      unpaid: 'Estimaciones por pagar',
      breakdown: 'Distribución por sección / concepto',
    },
    amounts: {
      contracted: 'Monto contratado',
      executed: 'Ejecutado (aprobado)',
      paid: 'Pagado',
      balance: 'Saldo por pagar',
    },
    anticipo: {
      granted: 'Anticipo otorgado',
      amortized: 'Amortizado',
      remaining: 'Saldo de anticipo',
      percentage: 'Porcentaje',
    },
    unpaid: {
      empty: 'Sin estimaciones pendientes de pago.',
      number: 'Estimación No.',
      period: 'Periodo',
      amount: 'Total a pagar',
      markPaid: 'Marcar como pagada',
    },
    payModal: {
      title: 'Comprobante de pago',
      hint: 'Sube el comprobante de pago antes de confirmar. El archivo quedará en la carpeta "Comprobantes de pago".',
      dropzone: 'Arrastra el archivo aquí o haz clic para seleccionar',
      dropzoneActive: 'Suelta el archivo…',
      uploading: 'Subiendo…',
      uploaded: 'Archivo listo',
      change: 'Cambiar archivo',
      confirm: 'Confirmar pago',
      skip: 'Confirmar sin comprobante',
      optional: 'El comprobante es opcional pero se recomienda adjuntarlo.',
    },
    breakdown: {
      noSection: 'Sin sección',
      total: 'Total contratado',
    },
  },
} as const